---
- name: Update packages cache
  apt:
    update_cache: yes
    cache_valid_time: "{{ packages_cache_valid_time }}"
  when: packages_update_cache | bool

- name: Add packages
  apt:
    name: "{{ item.name }}"
    install_recommends: "{{ item.install_recommended_packages | default(packages_install_recommended_packages) }}"
  loop: "{{ packages_to_add }}"

- name: Remove packages
  apt:
    name: "{{ item.name }}"
    state: absent
    purge: "{{ item.purge | default(packages_purge) }}"
  loop: "{{ packages_to_remove }}"