---
- name: Update packages cache
  apt:
    update_cache: yes
    cache_valid_time: "{{ packages_cache_valid_time }}"
  when: packages_update_cache | bool

- name: Add packages
  apt:
    name: "{{ item.name }}"
    install_recommends: "{{ item.install_recommended_packages | default(packages_default_install_recommended_packages) }}"
  loop: "{{ packages_to_add }}"

- name: Remove packages
  apt:
    name: "{{ item.name }}"
    state: absent
    purge: "{{ item.purge | default(packages_default_purge) }}"
  loop: "{{ packages_to_remove }}"

- name: Removed unused (outdated) packages
  apt:
    autoclean: yes
  when: packages_clean_system | bool

- name: Removed unused (automatically installed) packages
  apt:
    autoremove: yes
  when: packages_clean_system | bool